"""
Django settings for packet_mon project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*x18&#5_=tpn@l)#qs3sf)8wz9yt2rycaci&fsevnvgbuwe6kc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'packet_mon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'packet_mon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'network_monitor.db',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
TEMPLATES[0]['DIRS'] += [ BASE_DIR / 'monitor' / 'templates' ]
STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'monitor' / 'static' ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gnsmonitor9@gmail.com'
EMAIL_HOST_PASSWORD = 'qavjikcsbvcycrst'
ALERT_RECIPIENTS   = ['gnsmonitor9@gmail.com']  # list of email addresses

#GNS PROJECT ID
GNS_PROJECT_ID = 'acd0c89f-79ba-4294-8546-f4ee49fa8103' #'0cfc7a2c-815a-4a6e-aa01-ee62f09c93df'


#SNMP INFO
# Replace <ifIndex> with your interface index or pass in dynamically
IFHC_IN_OID    = '1.3.6.1.2.1.31.1.1.1.6.1'
IFHC_OUT_OID   = '1.3.6.1.2.1.31.1.1.1.10.1'

CPU_OID        = '1.3.6.1.2.1.25.3.3.1.2.1'
TOTAL_MEM_OID  = '1.3.6.1.4.1.2021.4.5.0'
AVAIL_MEM_OID  = '1.3.6.1.4.1.2021.4.6.0'
UPTIME_OID     = '1.3.6.1.2.1.1.3.0'
ICMP_IN_ERR_OID  = '1.3.6.1.2.1.5.14.0'
ICMP_OUT_ERR_OID = '1.3.6.1.2.1.5.15.0'


#Thresholds in percent
CPU_THRESHOLD    = 90.0 
MEM_THRESHOLD    = 80.0   

