# Generated by Django 5.2 on 2025-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_user_alter_device_ip_address_log_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='uptime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
