# Generated by Django 5.2 on 2025-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_metrics_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Informational')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('network', 'Network'), ('device', 'Device'), ('security', 'Security')], default='system', max_length=10),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='uptime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
