# Generated by Django 5.2 on 2025-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_log_acknowledged_log_severity_log_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gns3_node_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='gns3_project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
